<?php

/**
 * Implements weather_map_theme() hook.
 */
function weather_map_theme($existing, $type, $theme, $path) {

  return [
    'weather_map' => [
      'variables' => [],
    ],
  ];
}

/**
 * @param $page
 * @return void
 */
function weather_map_page_attachments_alter(&$page){
  $path = $current_path = \Drupal::service('path.current')->getPath();
  if($path == '/weather-map') {
    $page['#attached']['library'][] = 'weather_map/wm-library';
  }
}

/**
 * @return array[]
 */
function weather_map_permission() {
  return array(
    'administer my module' => array(
      'title' => t('Administer my module'),
      'description' => t('Perform administration tasks for my module.'),
    ),
  );
}
